#server
server:
  port: 3000

spring:
  profiles:
    active: local # 기본 환경 선택
  mvc:
    #view
    static-path-pattern: /static/**

# local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
security:
  signing-key: seonghwa

config:
    oauth2: 
      privateKey: adfadf

      publicKey: asdfadf